version: "3"
services:
  serviceserver:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    container_name: container_server
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./server:/app
  mysql:
    build: ./mysql
    restart: unless-stopped
    container_name: container_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: ayservice
      MYSQL_DATABASE: aydb